### ISSUE TITLE
Cannot extract downloaded dataset as it appears in binary form

### ISSUE THREAD

**Issue by sandyflute** [TwentyBN/smth-smth-v2-baseline-with-models#1]
Hi,
The data downloaded from the blog appears in binary format. How can i extract appropriately? 
I used this command 
`cat 20bn-something-something-v2-?? | tar zx`

Is there any other way to do this that i am missing ?

**Comment by raghavgoyal14** [comment]
I didn't understand completely - the above command didn't work?

**Comment by sandyflute** [comment]
Hi Raghav. it was a issue with the OS. The works Nicely.

**Comment by Fazlik995** [comment]
@sandyflute could you tell please, how did you solve the problem?

I have the issue

Thanks
